const constants = {
  REG_EX_LINE: /\r\n|\r|\n/,
  USE_STRICT: "use strict",
  ENCODING_UTF8: "utf8",
  LANGUAGE_JS: "javascript",
  LANGUAGE_SHORT_JS: "js",
  SCHEME_FILE: "file",
  SEMI_COLON: ";",
  COLON: ":",
  COMMA: ",",
  PERIOD: ".",
  BLANK: " ",
  NONE: "",
  EXCLAMATION_MARK: "!",
  SLASH: "/",
  EQUAL: "=",
  PLUS: "+",
  MINUS: "-",
  MULTIPLY: "*",
  DIVISION: "/",
  REMAIN: "%",
  NEW_LINE: "\n",
  LINE_COMMENT_DOUBLE_SLASH: "//",
  BLOCK_COMMENT_START: "/*",
  BLOCK_COMMENT_END: "*/",
  PARENTHESIS_START: "(",
  PARENTHESIS_END: ")",
  BRACKET_START: "[",
  BRACKET_END: "]",
  BRACE_START: "{",
  BRACE_END: "}",
  IMPORT_START: "import",
  IMPORT_EXP_JS: `js";`,
  IMPORT_END: "from",
  EXPORT: "export",
  EXPORT_DEFAULT: "export default",
  EXPRESSION_IF: "if (",
  EXPRESSION_ELSE_IF: "else if (",
  EXPRESSION_ELSE: "esle {",
  EXPRESSION_FOR: "for (",
  EXPRESSION_WHILE: "while (",
  EXPRESSION_FUNCTION: "function",
  STATEMENT_CONST: "const",
  STATEMENT_LET: "let",
  STATEMENT_VAR: "var",
  TYPE: "type",
  DECLARATION: "declaration",
  STRING: "string",
  BOOLEAN: "boolean",
  NUMBER: "number",
  NULL: "null",
  UNDEFINED: "undefined",
  OBJECT: "object",
  ARRAY: "array",
  TRUE: "true",
  FALSE: "false",
  LENGTH: "length",
};

module.exports = constants;
