const constants = {
  USE_STRICT: "use strict",
  LANGUAGE_JS: "javascript",
  SCHEME_FILE: "file",
  SEMI_COLON: ";",
  BLANK: " ",
  NONE: "",
  LINE_COMMENT_DOUBLE_SLASH: "//",
  BLOCK_COMMENT_START: "/*",
  BLOCK_COMMENT_END: "*/",
  EXCLAMATION_MARK: "!",
  ARRAY_START: "[",
  ARRAY_END: "]",
  OBJECT_START: "{",
  OBJECT_END: "}",
  TYPE: "type",
  DECLARATION: "declaration",
  STRING: "string",
  BOOLEAN: "boolean",
  NUMBER: "number",
  NULL: "null",
  UNDEFINED: "undefined",
  OBJECT: "object",
  ARRAY: "array",
  TRUE: "true",
  FALSE: "false",
};

module.exports = constants;
