const constants = {
  REG_EX_LINE: /\r\n|\r|\n/,
  USE_STRICT: "use strict",
  ENCODING_UTF8: "utf8",
  LANGUAGE_JS: "javascript",
  LANGUAGE_SHORT_JS: "js",
  SCHEME_FILE: "file",
  SEMI_COLON: ";",
  COMMA: ",",
  PERIOD: ".",
  BLANK: " ",
  NONE: "",
  EXCLAMATION_MARK: "!",
  SLASH: "/",
  EQUAL: "=",
  LINE_COMMENT_DOUBLE_SLASH: "//",
  BLOCK_COMMENT_START: "/*",
  BLOCK_COMMENT_END: "*/",
  ARRAY_START: "[",
  ARRAY_END: "]",
  OBJECT_START: "{",
  OBJECT_END: "}",
  IMPORT_START: "import",
  IMPORT_EXP_JS: `js";`,
  IMPORT_END: "from",
  EXPORT: "export",
  EXPORT_DEFAULT: "export default",
  TYPE: "type",
  DECLARATION: "declaration",
  STRING: "string",
  BOOLEAN: "boolean",
  NUMBER: "number",
  NULL: "null",
  UNDEFINED: "undefined",
  OBJECT: "object",
  ARRAY: "array",
  TRUE: "true",
  FALSE: "false",
};

module.exports = constants;
